/** Public, harness-neutral LoopGraph event protocol and state projection. */
export const harnessNeutral = true;

export { EVENT_VERSION, isValidEventEnvelope, isValidEventPayload, isValidRunEvent } from './events.js';
export type {
  AdmissionHitlDecidedEvent,
  AdmissionHitlDecidedPayload,
  AdmissionHitlRequestedEvent,
  AdmissionHitlRequestedPayload,
  AttemptId,
  EventEnvelope,
  EventId,
  EventVersion,
  GenerationId,
  GenerationPreparedEvent,
  GenerationPreparedPayload,
  GenerationPromotedEvent,
  GenerationPromotedPayload,
  HitlDecidedEvent,
  HitlDecidedPayload,
  HitlRequestId,
  HitlRequestedEvent,
  HitlRequestedPayload,
  LeaseAcquiredEvent,
  LeaseAcquiredPayload,
  NodeDispatchRequestedEvent,
  NodeDispatchRequestedPayload,
  NodeSettledEvent,
  NodeSettledPayload,
  NodeStartedEvent,
  NodeStartedPayload,
  PauseRequestedEvent,
  PauseRequestedPayload,
  RecoveryUncertainEvent,
  RecoveryUncertainPayload,
  RollbackAppliedEvent,
  RollbackAppliedPayload,
  RunCreatedEvent,
  RunCreatedPayload,
  RunEvent,
  RunEventType,
  RunId,
  RunPausedEvent,
  RunPausedPayload,
  RunResumedEvent,
  RunResumedPayload,
  ValidationId,
  ValidationRecordedEvent,
  ValidationRecordedPayload,
  ValidationSupersededEvent,
  ValidationSupersededPayload,
} from './events.js';
export { ReducerError, ReducerErrorCode } from './errors.js';
export { hasLoopEdge, isValidLoopSpec, sameLoopSpec, sameLoopSpecIdentity } from './loop-spec.js';
export type { LoopEdge, LoopNode, LoopSpec } from './loop-spec.js';
export type {
  ActiveAttempt,
  AdmissionHitlState,
  HitlState,
  LeaseView,
  PreparedGeneration,
  PromotedGeneration,
  RollbackAncestry,
  RunPhase,
  RunView,
  ValidationState,
} from './model.js';
export type {
  AdapterCallbackContext,
  ArtifactReference,
  ArtifactStore,
  CheckpointRead,
  CheckpointStore,
  CheckpointWrite,
  EventStore,
  ExecutionAdapter,
  ExecutionOutcome,
  GenerationManifest,
  HumanApprovalOutcome,
  HumanApprovalRequest,
  HumanGateAdapter,
  LeaseGrant,
  NamedArtifact,
  RecoveryInput,
  RecoveryOutput,
  RunLease,
  SupervisorClock,
  SupervisorLeaseTimer,
  SupervisorIdFactory,
  ValidationAdapter,
  ValidationOutcome,
} from './ports.js';
export type {
  CreateRunInput,
  DispatchAttemptInput,
  PrepareGenerationInput,
  PreparedArtifactInput,
  PromotePreparedGenerationInput,
  RecordAdmissionHitlDecisionInput,
  RecordHitlDecisionInput,
  RecoverRunInput,
  RequestAdmissionHitlInput,
  RequestHitlInput,
  RollbackInput,
  SupervisorDependencies,
} from './supervisor.js';
export { Supervisor } from './supervisor.js';
export { reduce } from './reducer.js';
